# 将 Gazebo Sim 时钟传给 ROS 2。
- ros_topic_name: '/clock'
  gz_topic_name: '/clock'
  ros_type_name: 'rosgraph_msgs/msg/Clock'
  gz_type_name: 'gz.msgs.Clock'
  direction: GZ_TO_ROS

# 将 ROS 2 速度指令传给麦轮驱动插件。
- ros_topic_name: '/cmd_vel'
  gz_topic_name: '/model/robot/cmd_vel'
  ros_type_name: 'geometry_msgs/msg/Twist'
  gz_type_name: 'gz.msgs.Twist'
  direction: ROS_TO_GZ

# 将麦轮驱动插件发布的里程计传给 ROS 2。
- ros_topic_name: '/odom'
  gz_topic_name: '/model/robot/odometry'
  ros_type_name: 'nav_msgs/msg/Odometry'
  gz_type_name: 'gz.msgs.Odometry'
  direction: GZ_TO_ROS

# 将 Gazebo 中真实转动的车轮关节状态传给 ROS 2 的 robot_state_publisher。
- ros_topic_name: '/joint_states'
  gz_topic_name: '/world/test_office/model/robot/joint_state'
  ros_type_name: 'sensor_msgs/msg/JointState'
  gz_type_name: 'gz.msgs.Model'
  direction: GZ_TO_ROS

# 将 MID360 三维点云传给 ROS 2。
- ros_topic_name: '/mid360/points'
  gz_topic_name: '/model/robot/mid360/points/points'
  ros_type_name: 'sensor_msgs/msg/PointCloud2'
  gz_type_name: 'gz.msgs.PointCloudPacked'
  frame_id: 'livox_frame'
  direction: GZ_TO_ROS
