# 将 Gazebo Sim 时钟传给 ROS 2。
- ros_topic_name: '/clock'
  gz_topic_name: '/clock'
  ros_type_name: 'rosgraph_msgs/msg/Clock'
  gz_type_name: 'gz.msgs.Clock'
  direction: GZ_TO_ROS

# 将 ROS 2 速度指令传给麦轮驱动插件。
- ros_topic_name: '/cmd_vel'
  gz_topic_name: '/model/robot/cmd_vel'
  ros_type_name: 'geometry_msgs/msg/Twist'
  gz_type_name: 'gz.msgs.Twist'
  direction: ROS_TO_GZ

# 将麦轮驱动插件发布的里程计传给 ROS 2。
- ros_topic_name: '/odom'
  gz_topic_name: '/model/robot/odometry'
  ros_type_name: 'nav_msgs/msg/Odometry'
  gz_type_name: 'gz.msgs.Odometry'
  direction: GZ_TO_ROS
